### ISSUE TITLE
ScrollViewWithStickyHeader doesn't pass 'showsIndicators' to ScrollViewWithOffsetTracking

### ISSUE THREAD

**Issue by im-murilo** [danielsaidi/ScrollKit#13]
When setting a ScrollViewWithStickyHeader's 'showsIndicators' to 'false', this value is not passed on to ScrollViewWithOffsetTracking, so it always defaults to showing indicators.

Current version:
`    var scrollView: some View {
        GeometryReader { proxy in
            ScrollViewWithOffsetTracking(onScroll: handleScrollOffset) {
                VStack(spacing: 0) {
                    scrollHeader
                    content()
                        .frame(maxHeight: .infinity)
                }
            }
            .onAppear {
                DispatchQueue.main.async {
                    navigationBarHeight = proxy.safeAreaInsets.top
                }
            }
        }
    }
`

Should be:
`    var scrollView: some View {
        GeometryReader { proxy in
            ScrollViewWithOffsetTracking(onScroll: handleScrollOffset, showsIndicators: showsIndicators) {
                VStack(spacing: 0) {
                    scrollHeader
                    content()
                        .frame(maxHeight: .infinity)
                }
            }
            .onAppear {
                DispatchQueue.main.async {
                    navigationBarHeight = proxy.safeAreaInsets.top
                }
            }
        }
    }
`

**Comment by danielsaidi** [comment]
Thanks to you, now they do! 🙌 

This is out in the just released 0.5.1.
