### ISSUE TITLE
Question: how can I use this library to dismiss a few on the pull down?

### ISSUE THREAD

**Issue by missphyrgames** [danielsaidi/ScrollKit#16]
Hey, firstly, thank you for creating this library and also writing up an informative blog post! I found it very interesting. I'm a beginner in swiftui so apologies if this is something that's easy to do.

I'm trying to dismiss a view when you reach the top of the scrollview (similar to how the netflix app does it, where you can scroll the list and then you can reach to the top without it dismissing, but if you then pull down again, it will dismiss the view). Would really appreciate any pointers and advice you can give!

**Comment by danielsaidi** [comment]
Hi @missphyrgames 

SwiftUI has built-in support for this. Just present your screen in a sheet, and you'll get that behavior.

Netflix are smart to use dark mode to make it less obvious that the movie screen is in a sheet.

**Comment by missphyrgames** [comment]
@danielsaidi thank you for the quick reply! I had a follow up question on this. How did they do the animation to open the clicked on movie with a sheet? I didn't think that was possible with matched geometry with a sheet?
