### ISSUE TITLE
Can i detect when ScrollView has finished scrolling?

### ISSUE THREAD

**Issue by gzlboy** [danielsaidi/ScrollKit#18]
I want to do something when scroll was finished.How can I do this? Thanks！

**Comment by danielsaidi** [comment]
Do you mean that when a scroll event ends and the offset stops updating?

**Comment by gzlboy** [comment]
Yes！I find a repository that implemented this feature:
https://github.com/fatbobman/IsScrolling

In addition to the scrolling state, it will be better if i can get the scrolling direction:)

**Comment by gzlboy** [comment]
Thanks! Look forward to this feature:)

**Comment by danielsaidi** [comment]
@gzlboy If you have the possibility to use iOS 18 and macOS 15, it has a new `.onScrollPhaseChange` modifier:

```swift
.onScrollPhaseChange { _, newPhase in
     ...
}
```

Since the SDKs scroll views use regular `ScrollView` underneath, you should be able to add this modifier to its content.
