### ISSUE TITLE
Draggable gesture 

### ISSUE THREAD

**Issue by DidarSeyidov** [danielsaidi/ScrollKit#20]
By using the package can I drag my large list to the end easily by scrollbar

**Comment by danielsaidi** [comment]
Hi @DidarSeyidov 

I'm not sure what you mean. This library has some additional utilities, which are actually now in SwiftUI from iOS 18 and later. It also adds some example views to show you how to use them.

**Comment by DidarSeyidov** [comment]
I mean the scrollbar in the library support draggable feature by hand or not

**Comment by danielsaidi** [comment]
Yes, it's a regular `ScrollView` 👍
