### ISSUE TITLE
Add support for large title

### ISSUE THREAD

**Issue by maxim-smotrov** [danielsaidi/ScrollKit#6]
The documentation says "This view enforces .navigationBarTitleDisplayMode(.inline) since a large title doesn’t work with a sticky header.".
Is there a technical limitation?
I can't switch to inline title in my app so it would be great to have large title supported by the lib.

**Comment by danielsaidi** [comment]
Hi @maxim-smotrov 

I guess it technically would *work* but it doesn't look that nice 😀
