### ISSUE TITLE
Question: TabView inside the ScrollViewWithStickyHeader 

### ISSUE THREAD

**Issue by gabrielribeiro** [danielsaidi/ScrollKit#9]
Congrats on the work! Such a stunning library! It definitely improved my app UI!

Just a question: is it possible to have a TabView (page control) inside the ScrollViewWithStickyHeader header and have all the gestures working?

I want to develop something like that:
<img width="638" alt="Screenshot 2023-12-03 at 23 09 14" src="https://github.com/danielsaidi/ScrollKit/assets/4466700/50a61644-44ea-40ff-b1e2-4972792b6874">

**Comment by danielsaidi** [comment]
Hey @gabrielribeiro 

Sure, it should work right away.

I basically just replaced the preview header in the `SpotifyPreviewScreen` with this:

```swift
func scrollViewHeader() -> some View {
    TabView {
        Color.red
        Color.green
        Color.blue
    }
    .tabViewStyle(.page)
}
```

and the result becomes:

<img width="350" alt="Skärmavbild 2023-12-04 kl  17 29 54" src="https://github.com/danielsaidi/ScrollKit/assets/429927/6a5ae1b8-4075-4afa-a691-f96c5328b6fd"> <img width="350" alt="Skärmavbild 2023-12-04 kl  17 29 57" src="https://github.com/danielsaidi/ScrollKit/assets/429927/823ad8db-9176-4290-8e9c-28c570af89e1">

**Comment by gabrielribeiro** [comment]
Wow that's awesome! Thank you so much for the help!

**Comment by danielsaidi** [comment]
Also, if you don't need the pinned behavior, you can just use the `ScrollViewHeader` inside a regular `ScrollView` :)

```swift
ScrollView {
    VStack {
        ScrollViewHeader {
            TabView {
                Color.red
                Color.green
                Color.blue
            }
            .tabViewStyle(.page)
        }
         .frame(height: 250)
                    
        LazyVStack {
            ForEach(0...100, id: \.self) {
                Text("\($0)")
            }
        }
    }
}
```

The result becomes:

<img width="250" alt="screen1" src="https://github.com/danielsaidi/ScrollKit/assets/429927/d10b6996-884e-447c-826c-f9f5623b40ba"> <img width="250" alt="screen2" src="https://github.com/danielsaidi/ScrollKit/assets/429927/aa5e9379-23cb-4516-939e-d59dcae1dc3b"> <img width="250" alt="screen3" src="https://github.com/danielsaidi/ScrollKit/assets/429927/63048822-949e-4fd4-b082-07f7713ed340">
